#!/usr/bin/env python3
"""Generate firmware/vial/oled_frames.h: 128x32 OLED frames, one per layer.

Each frame = WING logo on the left + 2x2 layer dots on the right
(filled = active layer; order: top-left, top-right, bottom-left, bottom-right).

Usage: .venv/bin/python firmware/tools/gen_oled.py [--preview]
Needs Pillow.
"""
import os
import sys

from PIL import Image, ImageDraw

W, H = 128, 32
LOGO = os.path.join(os.path.dirname(__file__), "wing_logo.png")
THRESHOLD = 140  # grey level below which a logo pixel is lit
TEXT_BOX = (0, 0, 98, H)  # area the wordmark is centred in
DOT_D, DOT_GAP = 10, 3    # dot size and gap between dots
DOT_R = 2                 # corner radius of the layer squares
OUT = os.path.join(os.path.dirname(__file__), "..", "vial", "oled_frames.h")


def wordmark():
    """WING logo (cropped from the protocol PDF cover) scaled into TEXT_BOX."""
    logo = Image.open(LOGO).convert("L")
    x0, y0, x1, y1 = TEXT_BOX
    scale = min((x1 - x0 - 4) / logo.width, (y1 - y0 - 6) / logo.height)
    w, h = round(logo.width * scale), round(logo.height * scale)
    small = logo.resize((w, h), Image.LANCZOS).point(lambda v: 255 if v < THRESHOLD else 0, "1")
    img = Image.new("1", (W, H), 0)
    img.paste(small, (x0 + (x1 - x0 - w) // 2, y0 + (y1 - y0 - h) // 2))
    return img


def frame(layer):
    img = wordmark()
    d = ImageDraw.Draw(img)
    grid = 2 * DOT_D + DOT_GAP
    gx = W - grid - 3
    gy = (H - grid) // 2
    for i in range(4):
        cx = gx + (i % 2) * (DOT_D + DOT_GAP)
        cy = gy + (i // 2) * (DOT_D + DOT_GAP)
        box = (cx, cy, cx + DOT_D - 1, cy + DOT_D - 1)
        d.rounded_rectangle(box, radius=DOT_R, fill=1 if i == layer else 0, outline=1)
    return img


def to_pages(img):
    """SSD1306 page layout: 4 pages of 128 columns, LSB = top pixel."""
    px = img.load()
    out = []
    for page in range(H // 8):
        for x in range(W):
            out.append(sum((1 << bit) for bit in range(8) if px[x, page * 8 + bit]))
    return out


def main():
    frames = [frame(l) for l in range(4)]
    if "--preview" in sys.argv:
        for l, f in enumerate(frames):
            print(f"layer {l}")
            px = f.load()
            for y in range(H):
                print("".join("#" if px[x, y] else "." for x in range(W)))
        return
    lines = [
        "// Generated by firmware/tools/gen_oled.py - do not edit.",
        "#pragma once",
        "",
        "static const char PROGMEM oled_frames[4][512] = {",
    ]
    for l, f in enumerate(frames):
        b = to_pages(f)
        lines.append(f"    {{ // layer {l}")
        for i in range(0, len(b), 16):
            lines.append("        " + ", ".join(f"0x{v:02x}" for v in b[i : i + 16]) + ",")
        lines.append("    },")
    lines.append("};")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
