#!/usr/bin/env python3
"""Generate firmware/vial/oled_frames.h: 128x32 OLED frames, one per layer, plus the BPM glyphs.

Each frame (left-aligned; the case hides the right edge) = WING logo + layer number (1-4) shown dark on a bright
rounded box on the right. The BPM screen (shown briefly after a tap tempo) is composed by the firmware from
big digit glyphs and a small "BPM" label, each stored column by column, 4 bytes (pages) per column.

Usage: .venv/bin/python firmware/tools/gen_oled.py [--preview]
Needs Pillow and DejaVuSans-Bold.ttf.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

W, H = 128, 32
LOGO = os.path.join(os.path.dirname(__file__), "wing_logo.png")
THRESHOLD = 140  # grey level below which a logo pixel is lit
LOGO_W = 94                      # logo width; everything is left-aligned
GAP = 4                          # space between logo and layer box
BOX_W, BOX_H, BOX_R = 24, 30, 3  # layer-number box size and corner radius
DIGIT_PX = 24                    # digit font size
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
BPM_PX = 31                      # BPM digit font size (digits ~23 px tall)
BPM_LABEL_PX = 11
GLYPHS = "0123456789."           # index 10 = '.', 11 = the "BPM" label
OUT = os.path.join(os.path.dirname(__file__), "..", "vial", "oled_frames.h")


def wordmark():
    """WING logo (cropped from the protocol PDF cover), left-aligned, vertically centred."""
    logo = Image.open(LOGO).convert("L")
    w = LOGO_W
    h = round(logo.height * w / logo.width)
    small = logo.resize((w, h), Image.LANCZOS).point(lambda v: 255 if v < THRESHOLD else 0, "1")
    img = Image.new("1", (W, H), 0)
    img.paste(small, (0, (H - h) // 2))
    return img


def frame(layer):
    """Logo + layer number (1-4) cut out of a bright rounded box on the right."""
    img = wordmark()
    d = ImageDraw.Draw(img)
    x0 = LOGO_W + GAP
    box = (x0, (H - BOX_H) // 2, x0 + BOX_W - 1, (H + BOX_H) // 2 - 1)
    d.rounded_rectangle(box, radius=BOX_R, fill=1)
    font = ImageFont.truetype(FONT, DIGIT_PX)
    text = str(layer + 1)
    l, t, r, b = d.textbbox((0, 0), text, font=font)
    x = box[0] + (box[2] - box[0] + 1 - (r - l)) // 2 - l
    y = box[1] + (box[3] - box[1] + 1 - (b - t)) // 2 - t
    d.text((x, y), text, font=font, fill=0)
    return img


def glyph(text, px, spacing):
    """1-bit 32 px tall image of `text`, cropped to its ink plus `spacing` columns. Digits share one
    baseline, centred vertically; the label sits on the digits' baseline."""
    font = ImageFont.truetype(FONT, px)
    big = ImageFont.truetype(FONT, BPM_PX)
    probe = ImageDraw.Draw(Image.new("1", (1, 1)))
    _, dt, _, db = probe.textbbox((0, 0), "0", font=big)      # digit ink top/bottom at BPM_PX
    y_base = (H - (db - dt)) // 2 - dt                        # y offset that centres the digits
    img = Image.new("1", (64, H), 0)
    d = ImageDraw.Draw(img)
    if px == BPM_PX:
        d.text((0, y_base), text, font=font, fill=1)
    else:  # label: bottom aligned with the digits' bottom
        _, lt, _, lb = d.textbbox((0, 0), text, font=font)
        d.text((0, y_base + db - lb), text, font=font, fill=1)
    l, _, r, _ = img.getbbox()
    out = Image.new("1", (r - l + spacing, H), 0)
    out.paste(img.crop((l, 0, r, H)), (0, 0))
    return out


def glyph_columns(img):
    px = img.load()
    cols = []
    for x in range(img.width):
        for page in range(H // 8):
            cols.append(sum((1 << bit) for bit in range(8) if px[x, page * 8 + bit]))
    return cols


def bpm_glyphs():
    return [glyph(c, BPM_PX, 2) for c in GLYPHS] + [glyph("BPM", BPM_LABEL_PX, 0)]


def bpm_preview(text, glyphs):
    img = Image.new("1", (W, H), 0)
    x = 0
    for c in text:
        g = glyphs[GLYPHS.index(c)]
        img.paste(g, (x, 0)); x += g.width
    img.paste(glyphs[-1], (x + 3, 0))
    return img


def to_pages(img):
    """SSD1306 page layout: 4 pages of 128 columns, LSB = top pixel."""
    px = img.load()
    out = []
    for page in range(H // 8):
        for x in range(W):
            out.append(sum((1 << bit) for bit in range(8) if px[x, page * 8 + bit]))
    return out


def main():
    frames = [frame(l) for l in range(4)]
    glyphs = bpm_glyphs()
    if "--preview" in sys.argv:
        for l, f in enumerate(frames + [bpm_preview("120.5", glyphs), bpm_preview("88.0", glyphs)]):
            print(f"frame {l}")
            px = f.load()
            for y in range(H):
                print("".join("#" if px[x, y] else "." for x in range(W)))
        return
    lines = [
        "// Generated by firmware/tools/gen_oled.py - do not edit.",
        "#pragma once",
        "",
        "static const char PROGMEM oled_frames[4][512] = {",
    ]
    for l, f in enumerate(frames):
        b = to_pages(f)
        lines.append(f"    {{ // layer {l}")
        for i in range(0, len(b), 16):
            lines.append("        " + ", ".join(f"0x{v:02x}" for v in b[i : i + 16]) + ",")
        lines.append("    },")
    lines.append("};")
    data, offs = [], []
    for g in glyphs:
        offs.append(len(data) // 4)
        data += glyph_columns(g)
    lines += ["", "// BPM screen glyphs: '0'-'9', '.', then the \"BPM\" label. Column-major, 4 bytes (pages) per column.",
              f"static const uint16_t bpm_glyph_col[{len(glyphs)}] = {{{', '.join(map(str, offs))}}};",
              f"static const uint8_t bpm_glyph_w[{len(glyphs)}] = {{{', '.join(str(g.width) for g in glyphs)}}};",
              f"static const uint8_t PROGMEM bpm_glyph_data[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in data[i : i + 16]) + ",")
    lines.append("};")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
