#!/usr/bin/env python3
"""Generate firmware/vial/oled_frames.h: 128x32 OLED frames, one per layer.

Each frame = WING logo on the left + layer number (1-4) shown dark on a bright
rounded box on the right.

Usage: .venv/bin/python firmware/tools/gen_oled.py [--preview]
Needs Pillow and DejaVuSans-Bold.ttf.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

W, H = 128, 32
LOGO = os.path.join(os.path.dirname(__file__), "wing_logo.png")
THRESHOLD = 140  # grey level below which a logo pixel is lit
TEXT_BOX = (0, 0, 98, H)  # area the wordmark is centred in
BOX_W, BOX_H, BOX_R = 24, 30, 3  # layer-number box size and corner radius
DIGIT_PX = 24                    # digit font size
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
OUT = os.path.join(os.path.dirname(__file__), "..", "vial", "oled_frames.h")


def wordmark():
    """WING logo (cropped from the protocol PDF cover) scaled into TEXT_BOX."""
    logo = Image.open(LOGO).convert("L")
    x0, y0, x1, y1 = TEXT_BOX
    scale = min((x1 - x0 - 4) / logo.width, (y1 - y0 - 6) / logo.height)
    w, h = round(logo.width * scale), round(logo.height * scale)
    small = logo.resize((w, h), Image.LANCZOS).point(lambda v: 255 if v < THRESHOLD else 0, "1")
    img = Image.new("1", (W, H), 0)
    img.paste(small, (x0 + (x1 - x0 - w) // 2, y0 + (y1 - y0 - h) // 2))
    return img


def frame(layer):
    """Logo + layer number (1-4) cut out of a bright rounded box on the right."""
    img = wordmark()
    d = ImageDraw.Draw(img)
    box = (W - BOX_W - 2, (H - BOX_H) // 2, W - 3, (H + BOX_H) // 2 - 1)
    d.rounded_rectangle(box, radius=BOX_R, fill=1)
    font = ImageFont.truetype(FONT, DIGIT_PX)
    text = str(layer + 1)
    l, t, r, b = d.textbbox((0, 0), text, font=font)
    x = box[0] + (box[2] - box[0] + 1 - (r - l)) // 2 - l
    y = box[1] + (box[3] - box[1] + 1 - (b - t)) // 2 - t
    d.text((x, y), text, font=font, fill=0)
    return img


def to_pages(img):
    """SSD1306 page layout: 4 pages of 128 columns, LSB = top pixel."""
    px = img.load()
    out = []
    for page in range(H // 8):
        for x in range(W):
            out.append(sum((1 << bit) for bit in range(8) if px[x, page * 8 + bit]))
    return out


def main():
    frames = [frame(l) for l in range(4)]
    if "--preview" in sys.argv:
        for l, f in enumerate(frames):
            print(f"layer {l}")
            px = f.load()
            for y in range(H):
                print("".join("#" if px[x, y] else "." for x in range(W)))
        return
    lines = [
        "// Generated by firmware/tools/gen_oled.py - do not edit.",
        "#pragma once",
        "",
        "static const char PROGMEM oled_frames[4][512] = {",
    ]
    for l, f in enumerate(frames):
        b = to_pages(f)
        lines.append(f"    {{ // layer {l}")
        for i in range(0, len(b), 16):
            lines.append("        " + ", ".join(f"0x{v:02x}" for v in b[i : i + 16]) + ",")
        lines.append("    },")
    lines.append("};")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
